# Generated by Django 4.2.7 on 2023-11-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='code',
        ),
        migrations.AddField(
            model_name='submission',
            name='code_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='memory_used',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='time_taken',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
